name: telegram_web_app
description: "Representation and implementation of telegram web/mini apps apis"
version: 0.3.3
repository: https://github.com/khamidjon-khamidov/flutter_telegram_web_app
homepage: https://github.com/khamidjon-khamidov/flutter_telegram_web_app

environment:
  sdk: ^3.6.0
  flutter: ">=3.22.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
